#print("Programming","Essentials","in", sep="***", end="...")
#print("Python", end="\n")
#print('Greg\'s book.')
#print('"Greg's book."')


print("Origin version")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")


print("reduce # of print")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")

print("Increase arrow size")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *            *")
print("*               *")
print("******       ******")
print("    *        *")
print("    *        *")
print("    *        *")
print("    *        *")
print("    **********")

print("Double arrow #1")
print("        *            *")
print("       * *          * *")
print("      *   *        *   *")
print("     *     *      *     *")
print("    ***   ***    ***   ***   ")
print("      *   *  " *2)
print("      *   *  " *2)
print("      *****  " *2)


print("Double arrow #2")
print("        *    " *2)
print("       * *   " *2)
print("      *   *  " *2)
print("     *     * " *2)
print("    ***   ***" *2)
print("      *   *  " *2)
print("      *   *  " *2)
print("      *****  " *2)